### ISSUE TITLE
Error on Data page on Admin Website

### ISSUE THREAD

**Issue by arezoop92** [uoForms/Admin-CANBeWell#13]
By selecting start date and end date on Data page, an error appears which makes users to refresh, logout and login again, this is a bug which should be fixed ASAP (There should be a try/catch code, in order to fix this issue)

**Comment by arezoop92** [comment]
Please follow up with @krishna1768

**Comment by AliVaseghnia** [comment]
@krishna1768 As noted by Arezoo, the code has to be changed so that when the wrong Start Date/End Date is entered (or any other problem with retrieving data from the database occurs), a warning is shown to the user instead of the error page.
To reproduce you can enter a date that is out of range.

**Comment by arezoop92** [comment]
This bug has been tested, and the data page shows this bug has been resolved.
