### ISSUE TITLE
Add columns on Data page

### ISSUE THREAD

**Issue by arezoop92** [uoForms/Admin-CANBeWell#14]
Add columns in the database and add columns on the output, so we can do unique users, sessions as well as clicks

**Comment by krishna1768** [comment]
It is ready for testing. @melikaeft will test the code from the branch of google_analytics in the App CanBeWell repo

**Comment by krishna1768** [comment]
This was fixed by adding new variables called userid and sessionid in app.jsx file and those variables are being read by the tracking js file using the clickable function.

**Comment by arezoop92** [comment]
This issue is resolved and closed.
