### ISSUE TITLE
Add the message "Invalid Date" 

### ISSUE THREAD

**Issue by arezoop92** [uoForms/Admin-CANBeWell#19]
Add this message to the data page of Admin website when an invalid date range is requested which can not be shown.

**Comment by krishna1768** [comment]
@arezoop92 I have added a message which says “Kindly select the valid dates”

**Comment by AliVaseghnia** [comment]
In some cases both the message and data are displayed:
![image](https://user-images.githubusercontent.com/19916509/98021279-240b7380-1dd2-11eb-82c7-1cc1d3ce181a.png)

**Comment by arezoop92** [comment]
whenever an invalid date range is requested which can not be shown, The data page shows  this message" Kindly select the valid dates", Also this bug "showing data columns from previous data search" is resolved.

**Comment by arezoop92** [comment]
@krishna1768  Instead of the message says "Kindly select the valid dates” , please change it to "Invalid Dates" and "No Data Available..."

**Comment by krishna1768** [comment]
It was fixed and tested. please refer to comments in #5

**Comment by arezoop92** [comment]
This issue is resolved and closed.
