### ISSUE TITLE
Error on Data page (Download Dataset)

### ISSUE THREAD

**Issue by arezoop92** [uoForms/Admin-CANBeWell#23]
when download dataset is clicked for the first time it shows an error , but when it's clicked for the second time it works, It is a bug which should be resolved.

**Comment by krishna1768** [comment]
It was done by fixed some bugs in the code in which data is converted to csv file. Earlier the data is not getting passed correctly and now it is fixed

**Comment by arezoop92** [comment]
This issue is resolved and closed.
