### ISSUE TITLE
Data visualization page (required steps)

### ISSUE THREAD

**Issue by arezoop92** [uoForms/Admin-CANBeWell#31]
1- Data analyzation and visualization (table or chart on visualization page)

2-Second line should be a link to Power BI folder on google drive: https://drive.google.com/drive/folders/1ugXQrabFfpAWFNGDLD5Su82KMPQQe3Nz

3-Third line should be a link to  Tableau folder on google drive: https://drive.google.com/drive/folders/1CD03UiWFPwyY5oAwn_IDO2TqeHbz6INx

**Comment by AliVaseghnia** [comment]
Work that has to be done for visualization, in three steps:

1. Show the images of the created visualizations, the Python code has to run on the server.

2. Have a button to run the Python script when it is clicked (Run Script button).

3. On data page, download a CSV file for the script that the Python script can read and generate PNG based on the downloaded file.

**Comment by arezoop92** [comment]
@nogun096 This step is not done (4-There should a button that says "generate report" when it is pressed, it should show a table or chart which the result opens on the same page at below.)

**Comment by arezoop92** [comment]
This issue is resolved and closed. (Generate button is mentioned in another issue)
