### ISSUE TITLE
Add Date List Check In Data Home Page

### ISSUE THREAD

**Issue by arezoop92** [uoForms/Admin-CANBeWell#5]
1-disable users from selecting start date that is later than the latest date in firebase database.
2-using try...catch... (or except...) coding blocks to catching error messages and give users a warning message instead of showing errors directly.

**Comment by krishna1768** [comment]
This was fixed using the try-catch block in the code. in the try block, if the selected dates are in the future it will raise an exception which would be caught in the catch block and display an error message using the message option in django

**Comment by arezoop92** [comment]
This issue is resolved and closed.
