### ISSUE TITLE
LinkChecker: View Detail Page

### ISSUE THREAD

**Issue by arezoop92** [uoForms/Admin-CANBeWell#66]
on View Detail Page, There is no need to have the purple navigator bar and" CANBeWell Admin, Data, Visualization, Linkchecker, Log out". Remove all of it.

Instead Add a message, for Example: LinkChecker Results For "Name of the File" separately for ( Topic-EN/ Test-EN/ Topic-FR/ Test-FR)

**Comment by francine2** [comment]
LinkChecker view detail page has been updated with the above changes.
