### ISSUE TITLE
Using Python To Create Report In Excel Files

### ISSUE THREAD

**Issue by arezoop92** [uoForms/Admin-CANBeWell#7]
1-import raw data to excel.
2-filter data in admin tool and when data is ready import it as excel files.

**Comment by Abigail6on** [comment]
- [x] Create Dash web page, currently localhost

- [x] Python visual page link to Dash page

- [ ] Firebase live data connection

- [ ] PowerBI link needs define @arezoop92  (I want to show PowerBI on the webpage)

- [x] Documentation update

- [ ] Chart.js exploring (anyone interested?)

We can have two ways to go. Dashboard with JS or Python.

**Comment by Abigail6on** [comment]
follow up by Krishna
